---
user: "apache2"
copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
sys_packages: [ 'curl', 'vim', 'git', 'ufw']

http_host: "your_domain"
http_conf: "your_domain.conf"
http_port: "{{ APACHE_PORT }}"
disable_default: true

create_containers: 4
default_container_name: docker
default_container_image: ubuntu
default_container_command: sleep 1d